from urllib.parse import urljoin


URL = "https://djinni.co/"
FILTER_FOR_VACANCIES = URL + "jobs/"
BASE_PYTHON_URL = "?primary_keyword=Python"
JOIN_MAIN_URL = urljoin(FILTER_FOR_VACANCIES, BASE_PYTHON_URL)
EXP_FILTERS = [
    "&exp_level=no_exp",
    "&exp_level=1y",
    "&exp_level=2y",
    "&exp_level=3y",
    "&exp_level=5y",
]
list_of_all_vacancies = []
python_frameworks = [
    "django",
    "python",
    "pandas",
    "numpy",
    "git",
    "aws",
    "flask",
    "api",
    "ux",
    "docker",
    "orm",
    "tensorflow",
    "terraform",
    "tableau",
    "sql",
    "sqlalchemy",
    "rest",
    "linux",
    "postgresql",
    "artificial intelligence",
    "js",
    "json",
    "machine learning",
    "react",
    "oop",
    "nosql",
    "networking",
    "fullstack",
    "microservice",
    "mongodb",
    "html",
    "css",
    "algorithms",
    "drf",
    "fastapi",
    "asyncio",
    "graphql",
    "power bi",
    "elasticsearch",
    "k8s",
    "ansible",
    "redis",
    "bash",
    "jira",
    "javascript",
    "devops",
    "laravel",
    "sass",
    "Celery",
    "pytorch",
    "keras",
    "beautifulsoup",
    "bs4",
    "selenium",
    "unit testing",
    "pytest",
    "macos",
    "microsoft",
    "windows",
    "ai",
    "scraper",
    "edr",
    "siem",
    "impala",
    "nifi",
    "oozie",
    "hbase",
    "unit test",
]

python_vacancies = [
    "integrator",
    "tech",
    "team",
    "lead",
    "developer",
    "engineer",
    "software",
    "backend",
    "frontend",
    "ml",
    "data science",
    "data analysis",
    "fullstack",
    "software",
    "devops",
]

cut_off = ["junior", "middle", "senior"]

new_list_with_info = []
